from config.icon import PATH_JOB_ICON, get_image
from game.buffs import AWAKENING_POTION, BERSERK_POTION, CONCENTRATION_POTION


class Job:
    def __init__(
        self,
        _id,
        name,
        previous_job=None,
        spawn_skill=[],
        buff_skill=[],
        buff_aspd=[],
    ):
        self.id = _id
        self.name = name
        self.previous_job = previous_job
        self.spawn_skill = spawn_skill
        self.buff_skill = buff_skill
        self.buff_aspd = buff_aspd
        self.icon = get_image(PATH_JOB_ICON, self.id)

    def __str__(self):
        return self.name


NOVICE = Job("NOVICE", "Aprendiz", buff_aspd=[CONCENTRATION_POTION])
SWORDMAN = Job("SWORDMAN", "Espadachim", NOVICE, buff_aspd=[AWAKENING_POTION, BERSERK_POTION])
MAGICIAN = Job("MAGICIAN", "Mago", NOVICE)
ARCHER = Job("ARCHER", "Arqueiro", NOVICE)
ACOLYTE = Job("ACOLYTE", "Noviço", NOVICE)
MERCHANT = Job("MERCHANT", "Mercador", NOVICE)
THIEF = Job("THIEF", "Gatuno", NOVICE)
KNIGHT = Job("KNIGHT", "Cavaleiro", SWORDMAN)
PRIEST = Job("PRIEST", "Sacerdote", ACOLYTE)
WIZARD = Job("WIZARD", "Bruxo", MAGICIAN)
BLACKSMITH = Job("BLACKSMITH", "Ferreiro", MERCHANT)
HUNTER = Job("HUNTER", "Caçador", ARCHER)
ASSASSIN = Job("ASSASSIN", "Caçador", THIEF)
KNIGHT_PECO = KNIGHT
CRUSADER = Job("CRUSADER", "Cavaleiro", SWORDMAN)
MONK = Job("MONK", "Monge", ACOLYTE)
SAGE = Job("SAGE", "Sábio", MAGICIAN)
ROGUE = Job("ROGUE", "Arruaceiro", THIEF)
ALCHEMIST = Job("ALCHEMIST", "Alquimista", MERCHANT)
BARD = Job("BARD", "Bardo", ARCHER)
DANCER = Job("DANCER", "Odalisca", ARCHER)
CRUSADER_PECO = CRUSADER
SUPERNOVICE = Job("SUPERNOVICE", "Super Noviço", NOVICE)
GUNSLINGER = Job("GUNSLINGER", "Justiceiro", NOVICE)
NINJA = Job("NINJA", "Ninja", NOVICE)
LORD_KNIGHT = Job("LORD_KNIGHT", "Lorde", KNIGHT)
HIGH_PRIEST = Job("HIGH_PRIEST", "Sumo Sacerdote", PRIEST)
HIGH_WIZARD = Job("HIGH_WIZARD", "Arquimago", WIZARD)
WHITESMITH = Job("WHITESMITH", "Mestre Ferreiro", BLACKSMITH)
SNIPER = Job("SNIPER", "Atirador de Elite", BLACKSMITH)
ASSASSIN_CROSS = Job("ASSASSIN_CROSS", "Algoz", BLACKSMITH)
LORD_KNIGHT_PECO = LORD_KNIGHT
PALADIN = Job("PALADIN", "Paladino", CRUSADER)
CHAMPION = Job("CHAMPION", "Mestre", MONK)
SCHOLAR = Job("SCHOLAR", "Professor", SAGE)
STALKER = Job("STALKER", "Desordeiro", ROGUE)
BIOCHEMIST = Job("BIOCHEMIST", "Criador", ALCHEMIST)
MINSTREL = Job("MINSTREL", "Menestrel", BARD)
GYPSY = Job("GYPSY", "Cigana", DANCER)
PALADIN_PECO = PALADIN
RUNE_KNIGHT = Job("RUNE_KNIGHT", "Cavaleiro Rúnico", LORD_KNIGHT)
WARLOCK = Job("WARLOCK", "Arcano", HIGH_WIZARD)
RANGER = Job("RANGER", "Sentinela", SNIPER)
ARCH_BISHOP = Job("ARCH_BISHOP", "Sentinela", HIGH_PRIEST)
MECHANIC = Job("MECHANIC", "Mecânico", WHITESMITH)
GUILLOTINE_CROSS = Job("GUILLOTINE_CROSS", "Sicário", WHITESMITH)
ROYAL_GUARD = Job("ROYAL_GUARD", "Guardão Real", PALADIN)
SORCERER = Job("SORCERER", "Feiticeiro", SCHOLAR)
MAESTRO = Job("MAESTRO", "Maestro", MINSTREL)
WANDERER = Job("WANDERER", "Musa", GYPSY)
SURA = Job("SURA", "Shura", CHAMPION)
GENETIC = Job("GENETIC", "Bioquímico", BIOCHEMIST)
SHADOW_CHASER = Job("SHADOW_CHASER", "Renegado", STALKER)
RUNE_KNIGHT_PECO = RUNE_KNIGHT
ROYAL_GUARD_PECO = ROYAL_GUARD
RANGER_WOLF = RANGER
MECHANIC_GEAR = MECHANIC
RUNE_KNIGHT_PECO_2 = RUNE_KNIGHT
RUNE_KNIGHT_PECO_3 = RUNE_KNIGHT
RUNE_KNIGHT_PECO_4 = RUNE_KNIGHT
RUNE_KNIGHT_PECO_5 = RUNE_KNIGHT

JOB_MAP = {
    0: NOVICE,
    4001: NOVICE,
    1: SWORDMAN,
    4002: SWORDMAN,
    2: MAGICIAN,
    4003: SWORDMAN,
    3: ARCHER,
    4004: ARCHER,
    4: ACOLYTE,
    4005: ACOLYTE,
    5: MERCHANT,
    4006: MERCHANT,
    6: THIEF,
    4007: THIEF,
    7: KNIGHT,
    4008: LORD_KNIGHT,
    4060: RUNE_KNIGHT,
    8: PRIEST,
    4009: HIGH_PRIEST,
    4063: ARCH_BISHOP,
    9: WIZARD,
    4010: HIGH_WIZARD,
    4061: WARLOCK,
    10: BLACKSMITH,
    4011: WHITESMITH,
    4064: MECHANIC,
    4087: MECHANIC_GEAR,
    11: HUNTER,
    4012: SNIPER,
    4062: RANGER,
    4085: RANGER_WOLF,
    12: ASSASSIN,
    4013: ASSASSIN_CROSS,
    4065: GUILLOTINE_CROSS,
    13: KNIGHT_PECO,
    4014: LORD_KNIGHT_PECO,
    4081: RUNE_KNIGHT_PECO,
    4089: RUNE_KNIGHT_PECO_2,
    4091: RUNE_KNIGHT_PECO_3,
    4093: RUNE_KNIGHT_PECO_4,
    4095: RUNE_KNIGHT_PECO_5,
    14: CRUSADER,
    4015: PALADIN,
    4073: ROYAL_GUARD,
    15: MONK,
    4016: CHAMPION,
    4077: SURA,
    16: SAGE,
    4017: SCHOLAR,
    4074: SORCERER,
    17: ROGUE,
    4018: STALKER,
    4079: SHADOW_CHASER,
    18: ALCHEMIST,
    4019: BIOCHEMIST,
    4078: GENETIC,
    19: BARD,
    4020: MINSTREL,
    4075: MAESTRO,
    20: DANCER,
    4021: GYPSY,
    4076: WANDERER,
    21: CRUSADER_PECO,
    4022: PALADIN_PECO,
    4083: ROYAL_GUARD_PECO,
    23: SUPERNOVICE,
    24: GUNSLINGER,
    25: NINJA,
}

JOB_GROUPS = {
    "Início": [NOVICE],
    "Classe 1": [SWORDMAN, MAGICIAN, ARCHER, ACOLYTE, MERCHANT, THIEF],
    "Classe 2": [KNIGHT, PRIEST, WIZARD, BLACKSMITH, HUNTER, ASSASSIN, CRUSADER, MONK, SAGE, ROGUE, ALCHEMIST, BARD, DANCER, SUPERNOVICE, GUNSLINGER, NINJA],
    "Transclasse": [LORD_KNIGHT, HIGH_PRIEST, HIGH_WIZARD, WHITESMITH, SNIPER, ASSASSIN_CROSS, PALADIN, CHAMPION, SCHOLAR, STALKER, BIOCHEMIST, MINSTREL, GYPSY],
}
